FROM pytorch/pytorch

RUN apt-get update
RUN apt-get install -y unzip

# Install protobuf and the compiler
RUN curl -s -OL https://github.com/google/protobuf/releases/download/v3.2.0/protoc-3.2.0-linux-x86_64.zip
RUN unzip protoc-3.2.0-linux-x86_64.zip -d protoc3
RUN mv protoc3/bin/* /usr/local/bin/
RUN mv protoc3/include/* /usr/local/include/

# Install gRPC tools in Python
RUN pip install grpcio-tools
