FROM tensorflow/tensorflow:1.13.1-py3
# For GPU version, use:
# FROM tensorflow/tensorflow:1.13.1-gpu-py3
# for pytorch, use:
# FROM pytorch/pytorch

RUN apt-get update
RUN apt-get install -y unzip curl

# Install gRPC tools in Python
RUN pip install grpcio-tools

# Install the Kubernetes Python client
RUN pip install kubernetes

# Install RecordIO and its dependency
COPY recordio-0.0.1-py3-none-any.whl /recordio-0.0.1-py3-none-any.whl
RUN apt-get install -y libsnappy-dev && \
    pip install python-snappy crc32c && \
    pip install /recordio-0.0.1-py3-none-any.whl && \
    rm -f /recordio-0.0.1-py3-none-any.whl
