apiVersion: v1
kind: Pod
metadata:
  name: elasticdl-test-mnist-with-tb-master
  labels:
    app: elasticdl
    elasticdl_job_name: test-mnist-with-tb
spec:
  containers:
  - name: mnist-demo-container
    image: gcr.io/elasticdl/elasticdl:tb-dev
    command: ["/bin/bash"]
    args:
    - -c
    - >
      python -m elasticdl.python.elasticdl.master.main
      --model_file=/elasticdl/python/examples/mnist_functional_api.py
      --training_data_dir=/data/mnist/train
      --evaluation_data_dir=/data/mnist/test
      --records_per_task=100
      --num_epochs=1
      --grads_to_wait=10
      --minibatch_size=64
      --num_workers=2
      --checkpoint_steps=10
      --worker_image=gcr.io/elasticdl/elasticdl:tb-dev
      --job_name=test-mnist-with-tb
      --log_level=INFO
      --image_pull_policy=Always
      --tensorboard_log_dir=/tensorboard-log
    imagePullPolicy: Always
    env:
      - name: MY_POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
  restartPolicy: Never
