apiVersion: v1
kind: Service
metadata:
  labels:
    elasticdl_job_name: test-mnist
  name: tensorboard
spec:
  ports:
  - port: 80
    targetPort: 6006
  selector:
    elasticdl_job_name: test-mnist
  type: LoadBalancer
