package(default_visibility = ["//python:__subpackages__"])

py_library(
    name = "lib",
    srcs = [
        "__init__.py",
    ],
    deps = [
        "//python/elasticdl/tflib/ps:lib",
        "//python/elasticdl/tflib/worker:lib",
    ],
)
