ARG BASE_IMAGE=tensorflow/tensorflow:2.0.0b1-py3
# Use tensorflow/tensorflow:2.0.0b1-gpu-py3 if you want GPU-support.
FROM ${BASE_IMAGE}

# Replace the Splash screen from TensorFlow image.
COPY elasticdl/docker/bashrc /etc/bash.bashrc
RUN chmod a+rwx /etc/bash.bashrc

RUN apt-get update && apt-get install -y unzip curl git

COPY elasticdl/requirements.txt /requirements.txt
ARG EXTRA_PYPI_INDEX
RUN pip install -r /requirements.txt --extra-index-url=${EXTRA_PYPI_INDEX}
RUN pip install pre-commit --extra-index-url=${EXTRA_PYPI_INDEX}

# Copy the data generation package to /var and run them from there.
# This assumes that the data generation package is independent with the
# rest part of ElasticDL.  The generated data will be in /data.
COPY elasticdl/python/data/recordio_gen/image_label.py /var/image_label.py
RUN python /var/image_label.py --dataset mnist --fraction 0.25 \
	--records_per_shard 4096 /data && \
    rm -rf /root/.keras/datasets

# Copy the model zoo
COPY model_zoo /model_zoo
