ARG BASE_IMAGE=tensorflow/tensorflow:2.0.0b0-py3
FROM ${BASE_IMAGE}

RUN apt-get update && apt-get install -y unzip curl

ARG EXTRA_PYPI_INDEX

# Install RecordIO 
RUN pip install 'pyrecordio>=0.0.6' --extra-index-url=${EXTRA_PYPI_INDEX}

COPY elasticdl/python/data /elasticdl/python/data

ENV PYTHONPATH=/
WORKDIR /
RUN python elasticdl/python/data/recordio_gen/mnist/gen_data.py --codec_type tf_example /data
RUN python elasticdl/python/data/recordio_gen/cifar10/gen_data.py --codec_type tf_example /data

COPY elasticdl/docker/bashrc /etc/bash.bashrc
RUN chmod a+rwx /etc/bash.bashrc
