FROM ubuntu:16.04

RUN apt-get update && apt-get  -y --no-install-recommends install \
    unzip \
    curl \
    git \
    python3-pip

RUN ln -s /usr/bin/python3 /usr/bin/python && pip3 install --upgrade pip

# Install Golang
ARG GO_VERSION=1.12
RUN curl -Lv -o golang.tar.gz https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz && \
    tar -C /usr/local -xzvf golang.tar.gz && \
    rm golang.tar.gz
ENV PATH /usr/local/go/bin:$PATH

# Install ProtoC
ARG PROTOBUF_VERSION=3.6.1
RUN curl -Lv -o protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOBUF_VERSION}/protoc-${PROTOBUF_VERSION}-linux-x86_64.zip && \
    unzip protoc.zip -d /usr/local/protobuf
ENV PATH /usr/local/protobuf/bin:$PATH

# Install Protobuf Golang support
ENV GOPATH=/go_tmp
RUN mkdir /go_tmp && go get github.com/golang/protobuf/protoc-gen-go && mv /go_tmp/bin/protoc-gen-go /usr/local/bin && rm -fr /go_tmp

# Install Protobuf python support
RUN pip3 install grpcio-tools

# Note: user's go directory should be mount to /go in the container.
ENV GOPATH=/go
ENV PATH /go/bin:$PATH
