package(default_visibility = ["//python:__subpackages__"])

py_library(
    name = "lib",
    srcs = [
        "__init__.py",
    ],
    deps = [
        "//python/elasticdl/tflib:lib",
        "//python/elasticdl/system:lib",
    ],
)
